name: Jrcconstela
description: Web Apps Developer
meta_description: "Jose Constela, Web Apps Developer"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

baseurl:			'/'
url:            	'blog url'
author:         	'Jose Constela'
authorDescription: 	'Lol'
authorAvatar:		'https://pbs.twimg.com/profile_images/1979866278/photoCV.jpg'

# Style
cover:				'/assets/headers/london_bg.jpg'