# General
name: 				'Jrcconstela'
description: 		'Web Apps Developer'
meta_description: 	'Jose Constela, Web Apps Developer'
baseurl:			'/'
url:            	'blog url'

# Author
author:         	'Jose Constela'
authorDescription: 	'Lol'
authorAvatar:		'https://pbs.twimg.com/profile_images/1979866278/photoCV.jpg'

# Setup
markdown: 			'redcarpet'
highlighter: 		true
paginate: 			15

# comments
disqus:				'jrcconstela-github'

# Style
logo: 				false
cover:				'/assets/headers/london_bg.jpg'

# Tracking

# googleAnalytics:	false